
#   Source Code: https://github.com/AdamBurdik/Castle-Siege
#
#   THIS PLUGIN DOES NOT SUPPORT LEGACY FORMATTING ( &6, &l etc. )
#   PLEASE USE KYORI-ADVENTURE FORMAT: https://docs.advntr.dev/minimessage/format.html


# Maximum amount of players in one team
max_players_per_team: 16

START:
    # Minimum amount of players in one team to start the game
    min_players_per_team: 5
    # Countdown duration in seconds before starting the game ( in seconds )
    cooldown: 10

    title_fade_in: 0
    title_stay: 500
    title_fade_out: 250

DEFENDERS:
    name: "Franks"
    king_health: 80

ATTACKERS:
    name: "Vikings"

